spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/passlock
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true

passvault:
  security:
    salt: 9d472cb7-e7d4-4b3e-b406-f418b03a3877
